//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class price_range
    {
        public int id { get; set; }
        public string price_range_name { get; set; }
        public Nullable<decimal> min_price { get; set; }
        public Nullable<decimal> max_price { get; set; }
        public string description { get; set; }
        public bool isActive { get; set; }
        public System.DateTime created_at { get; set; }
        public System.DateTime update_at { get; set; }
    }
}
