//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class spa_basic_info
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public spa_basic_info()
        {
            this.spa_images = new HashSet<spa_images>();
            this.spa_time = new HashSet<spa_time>();
            this.spa_prices = new HashSet<spa_prices>();
        }

        [Key]
        public long id { get; set; }
        public string name { get; set; }
        public Nullable<long> cityId { get; set; }
        public string info_about { get; set; }
        public string website_url { get; set; }
        public string address { get; set; }
        public bool is_active { get; set; }
        public System.DateTime created_at { get; set; }
        public System.DateTime updated_at { get; set; }
        public string contact_name { get; set; }
        public string contact_email { get; set; }
        public string contact_no { get; set; }
        public string zipcode { get; set; }
    
        public virtual city city { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<spa_images> spa_images { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<spa_time> spa_time { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<spa_prices> spa_prices { get; set; }
    }
}
