//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class spa_images
    {
        public long id { get; set; }
        public long spa_id { get; set; }
        public string image_url { get; set; }
        public Nullable<int> seq_no { get; set; }
        public bool is_default { get; set; }
        public System.DateTime created_at { get; set; }
        public System.DateTime updated_at { get; set; }
    
        public virtual spa_basic_info spa_basic_info { get; set; }
    }
}
