//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class spa_dbEntities : DbContext
    {
        public spa_dbEntities()
            : base("name=spa_dbEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<city> citys { get; set; }
        public virtual DbSet<CategeogySubCategory> CategeogySubCategories { get; set; }
        public virtual DbSet<spa_basic_info> spa_basic_info { get; set; }
        public virtual DbSet<spa_images> spa_images { get; set; }
        public virtual DbSet<spa_time> spa_time { get; set; }
        public virtual DbSet<price_range> price_range { get; set; }
        public virtual DbSet<spa_prices> spa_prices { get; set; }
    }
}
